const CACHE_NAME="language-teacher-shell-v28";
const APP_SHELL=[
"./","./index.html","./manifest.webmanifest","./update.json","./deployment-config.js",
"./src/app/app.js","./src/app/router.js","./src/app/state.js","./src/app/version.js","./src/app/update-manager.js","./src/app/release-check.js","./src/app/release-check-summary.js","./src/i18n/i18n.js",
"./src/language/language-catalog.js","./src/language/profile-engine.js","./src/learning/models.js","./src/learning/learning-repository.js","./src/learning/mistake-engine.js","./src/learning/grammar-focus.js","./src/learning/srs-engine.js","./src/learning/review-engine.js","./src/learning/session-engine.js","./src/learning/progress-engine.js","./src/learning/conversation-engine.js","./src/learning/real-life-engine.js",
"./src/ai/provider.js","./src/ai/local-demo-provider.js","./src/ai/proxy-provider.js","./src/ai/proxy-config.js","./src/ai/context-builder.js","./src/ai/response-contract.js","./src/ai/response-parser.js","./src/ai/teacher-engine.js",
"./src/speech/speech-provider.js","./src/speech/browser-speech-provider.js","./src/speech/recorder.js","./src/speech/synthesis.js","./src/speech/recognition.js","./src/speech/pronunciation.js","./src/speech/speech-manager.js",
"./src/storage/db.js","./src/storage/schema.js","./src/storage/migrations.js","./src/storage/backup.js","./src/storage/backup-validation.js","./src/storage/restore.js",
"./src/ui/components/app-header.js","./src/ui/components/bottom-nav.js","./src/ui/components/language-onboarding.js","./src/ui/components/update-notice.js","./src/ui/components/operation-notice.js","./src/ui/components/voice-recorder.js",
"./src/ui/screens/today.js","./src/ui/screens/practice.js","./src/ui/screens/session.js","./src/ui/screens/speech.js","./src/ui/screens/teacher.js","./src/ui/screens/conversation.js","./src/ui/screens/real-life.js","./src/ui/screens/review.js","./src/ui/screens/words.js","./src/ui/screens/progress.js","./src/ui/screens/settings.js",
"./src/ui/styles/tokens.css","./src/ui/styles/base.css","./src/ui/styles/layout.css","./src/ui/styles/components.css","./src/ui/styles/responsive.css","./src/ui/styles/review.css","./src/ui/styles/session-update.css","./src/ui/styles/speech.css","./src/ui/styles/teacher.css","./src/ui/styles/conversation.css","./src/ui/styles/real-life.css","./src/ui/styles/release.css","./src/ui/styles/today-intelligence.css","./src/ui/styles/library.css","./src/ui/styles/progress-meaningful.css","./src/ui/styles/practice-guided.css","./src/ui/styles/ai-deployment.css",
"./assets/icons/icon-192.png","./assets/icons/icon-512.png"];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(APP_SHELL))));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE_NAME).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));
self.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting()});
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url);if(u.pathname.endsWith("/update.json")||u.pathname.endsWith("/deployment-config.js")){e.respondWith(fetch(e.request,{cache:"no-store"}).catch(()=>caches.match(e.request)));return;}if(e.request.mode==="navigate"){e.respondWith(fetch(e.request).catch(()=>caches.match("./index.html")));return;}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(!r||r.status!==200||r.type==="opaque")return r;const copy=r.clone();caches.open(CACHE_NAME).then(cache=>cache.put(e.request,copy));return r;})));});
