import {DEFAULT_USER_ID} from "../storage/schema.js";
const now=()=>new Date().toISOString();
const uid=prefix=>`${prefix}-${globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}`;
const required=(value,name)=>{if(value===undefined||value===null||value==="")throw new Error(`${name} is required`);return value;};
const strength=value=>Math.max(0,Math.min(1,Number(value)||0));
export function createLearningItem(input){const createdAt=now();return{id:input.id??uid("item"),userId:input.userId??DEFAULT_USER_ID,languageId:required(input.languageId,"languageId"),type:input.type??"chunk",text:required(input.text,"text"),meaning:input.meaning??"",register:input.register??"neutral",contexts:Array.isArray(input.contexts)?input.contexts:[],tags:Array.isArray(input.tags)?input.tags:[],skills:Array.isArray(input.skills)?input.skills:[],memory:{recognition:strength(input.memory?.recognition),production:strength(input.memory?.production),listening:strength(input.memory?.listening),pronunciation:strength(input.memory?.pronunciation)},introducedAt:input.introducedAt??createdAt,lastSeenAt:input.lastSeenAt??null,nextReviewAt:input.nextReviewAt??null,createdAt,updatedAt:createdAt};}
export function createMistake(input){const createdAt=now();return{id:input.id??uid("mistake"),userId:input.userId??DEFAULT_USER_ID,languageId:required(input.languageId,"languageId"),original:required(input.original,"original"),correct:required(input.correct,"correct"),category:input.category??"other",pattern:input.pattern??null,severity:input.severity??"medium",count:Number(input.count)||1,firstSeenAt:input.firstSeenAt??createdAt,lastSeenAt:input.lastSeenAt??createdAt,status:input.status??"active",createdAt,updatedAt:createdAt};}
export function createSession(input){const createdAt=now();return{id:input.id??uid("session"),userId:input.userId??DEFAULT_USER_ID,languageId:required(input.languageId,"languageId"),topic:input.topic??"",targetDuration:Number(input.targetDuration)||10,status:input.status??"planned",blocks:Array.isArray(input.blocks)?input.blocks:[],createdAt,updatedAt:createdAt,completedAt:input.completedAt??null};}
export function createPersonalSituation(input){const createdAt=now();return{id:input.id??uid("situation"),userId:input.userId??DEFAULT_USER_ID,languageId:required(input.languageId,"languageId"),title:required(input.title,"title"),description:input.description??"",status:input.status??"active",createdAt,updatedAt:createdAt};}
export function createProgressRecord(input){const createdAt=now(),languageId=required(input.languageId,"languageId"),skills=input.skills??{};return{id:input.id??`${input.userId??DEFAULT_USER_ID}:${languageId}`,userId:input.userId??DEFAULT_USER_ID,languageId,skills:{speaking:strength(skills.speaking),listening:strength(skills.listening),pronunciation:strength(skills.pronunciation),vocabulary:strength(skills.vocabulary),grammar:strength(skills.grammar)},capabilities:input.capabilities??{},createdAt,updatedAt:createdAt};}
export const LEARNING_ITEM_TYPES=["word","chunk","phrase","grammar-pattern","pronunciation-item","listening-item","situation-expression"];
