export function renderWords(state){
  const summary=state.learningSummary??{},active=state.languageProfiles.find(p=>p.languageId===state.activeLanguageId);
  if(!active)return `<section class="stack-lg"><div class="page-intro"><p class="eyebrow">LEARNING LIBRARY</p><h2>Сначала добавьте язык</h2><p class="muted">Вся учебная библиотека принадлежит конкретному языковому профилю.</p></div></section>`;
  const library=summary.library??{items:[],mistakes:[],situations:[]},items=library.items??[],mistakes=library.mistakes??[],situations=library.situations??[];
  return `<section class="stack-lg learning-library"><div class="page-intro"><p class="eyebrow">${active.flag} LEARNING LIBRARY</p><h2>Язык, который уже стал вашим материалом</h2><p class="muted">Здесь собраны выражения, известные ошибки и реальные ситуации из вашей практики. Материал возвращается в Review и будущие занятия.</p></div><div class="library-overview">${overview("Выражения",items.length)}${overview("Активные ошибки",mistakes.length)}${overview("Ситуации",situations.length)}${overview("К повторению",summary.dueReviews??0)}</div>${items.length?renderItems(items):emptyLibrary(state)}${mistakes.length?renderMistakes(mistakes):""}${situations.length?renderSituations(situations):""}</section>`;
}
function renderItems(items){const groups=groupItems(items);return `<section class="library-section"><div class="section-heading library-heading"><div><p class="eyebrow">USABLE LANGUAGE</p><h3>Выражения и паттерны</h3></div><span class="library-count">${items.length}</span></div><div class="library-groups">${groups.map(group=>`<details class="library-group" ${groups.length===1?"open":""}><summary><span>${escapeHtml(group.label)}</span><span>${group.items.length}</span></summary><div class="library-item-list">${group.items.map(renderLearningItem).join("")}</div></details>`).join("")}</div></section>`;}
function renderLearningItem(item){const memory=memorySummary(item.memory),contexts=(item.contexts??[]).slice(0,3);return `<article class="learning-item-card"><div class="learning-item-main"><div><span class="library-type">${escapeHtml(typeLabel(item.type))}</span><h4>${escapeHtml(item.text)}</h4>${item.meaning?`<p>${escapeHtml(item.meaning)}</p>`:""}</div><div class="memory-badge ${memory.className}"><strong>${memory.percent}%</strong><span>${memory.label}</span></div></div><div class="learning-item-meta">${item.register&&item.register!=="neutral"?`<span>${escapeHtml(registerLabel(item.register))}</span>`:""}${contexts.map(c=>`<span>${escapeHtml(c)}</span>`).join("")}<span>${reviewLabel(item.nextReviewAt)}</span></div><div class="memory-dimensions">${dimension("Узнаю",item.memory?.recognition)}${dimension("Говорю",item.memory?.production)}${dimension("Слышу",item.memory?.listening)}${dimension("Произношу",item.memory?.pronunciation)}</div></article>`;}
function renderMistakes(mistakes){return `<section class="library-section"><div class="section-heading library-heading"><div><p class="eyebrow">MISTAKE MEMORY</p><h3>То, к чему стоит вернуться</h3></div><span class="library-count">${mistakes.length}</span></div><div class="mistake-list">${mistakes.map(m=>`<article class="mistake-card"><div class="mistake-change"><span><small>Было</small><strong>${escapeHtml(m.original)}</strong></span><span class="mistake-arrow">→</span><span><small>Лучше</small><strong>${escapeHtml(m.correct)}</strong></span></div><div class="learning-item-meta"><span>${escapeHtml(m.category??"ошибка")}</span><span>${escapeHtml(severityLabel(m.severity))}</span><span>встречалась ${Number(m.count)||1}×</span></div></article>`).join("")}</div></section>`;}
function renderSituations(situations){return `<section class="library-section"><div class="section-heading library-heading"><div><p class="eyebrow">REAL LIFE</p><h3>Ваши жизненные ситуации</h3></div><span class="library-count">${situations.length}</span></div><div class="situation-library-grid">${situations.map(s=>`<article class="situation-library-card"><strong>${escapeHtml(s.title)}</strong>${s.description?`<p>${escapeHtml(s.description)}</p>`:""}<small>Будет использоваться в будущей практике</small></article>`).join("")}</div></section>`;}
function emptyLibrary(state){const hasData=(state.learningSummary?.sessions??0)>0||(state.learningSummary?.situations??0)>0;return `<article class="empty-state library-empty"><div class="empty-icon">Aa</div><h3>${hasData?"Первые выражения появятся после следующей практики":"Библиотека пока пустая"}</h3><p>${hasData?"Language Teacher сохраняет только материал, который действительно возник в ваших занятиях и жизненных ситуациях.":"Начните Today Session, Conversation или Real Life — полезный материал будет собираться здесь автоматически."}</p><button class="primary-button library-empty-action" type="button" data-route="practice">Перейти к практике</button></article>`;}
function overview(label,value){return `<article><strong>${value}</strong><span>${escapeHtml(label)}</span></article>`;}
function groupItems(items){const order=["chunk","phrase","situation-expression","grammar-pattern","word","pronunciation-item","listening-item"],map=new Map();items.forEach(item=>{const key=item.type??"chunk";if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return [...map.entries()].sort(([a],[b])=>(order.indexOf(a)<0?99:order.indexOf(a))-(order.indexOf(b)<0?99:order.indexOf(b))).map(([type,groupItems])=>({label:typePluralLabel(type),items:groupItems}));}
function memorySummary(memory={}){const values=["recognition","production","listening","pronunciation"].map(k=>Number(memory[k])||0),avg=values.reduce((a,b)=>a+b,0)/values.length,percent=Math.round(avg*100);if(avg>=.7)return{percent,label:"уверенно",className:"is-strong"};if(avg>=.45)return{percent,label:"развивается",className:"is-growing"};return{percent,label:"нужно повторять",className:"is-weak"};}
function dimension(label,value){const percent=Math.round((Number(value)||0)*100);return `<span><i style="width:${percent}%"></i><small>${escapeHtml(label)}</small></span>`;}
function reviewLabel(value){if(!value)return "повторение ещё не назначено";const date=new Date(value);if(Number.isNaN(date.getTime()))return "повторение запланировано";const diff=Math.ceil((date.getTime()-Date.now())/86400000);if(diff<=0)return "пора повторить";if(diff===1)return "повторить завтра";if(diff<7)return `повторить через ${diff} дн.`;return `повторить ${date.toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}`;}
function typeLabel(type){return ({word:"слово",chunk:"chunk",phrase:"фраза","grammar-pattern":"грамматика","pronunciation-item":"произношение","listening-item":"аудирование","situation-expression":"из ситуации"})[type]??"выражение";}
function typePluralLabel(type){return ({word:"Слова",chunk:"Chunks",phrase:"Фразы","grammar-pattern":"Грамматические паттерны","pronunciation-item":"Произношение","listening-item":"Аудирование","situation-expression":"Фразы из реальных ситуаций"})[type]??"Другие выражения";}
function registerLabel(r){return ({formal:"формально",informal:"разговорно",colloquial:"разговорно"}[r]??r)}
function severityLabel(v){return ({low:"небольшая",medium:"важная",high:"приоритетная"}[v]??"важная")}
function escapeHtml(value=""){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
